---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure RabbitMQ
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        # - 22
        # - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
    - name: Ubuntu
      versions:
        - bionic
        # - trusty
        - xenial
    - name: Debian
      versions:
        - buster
        - stretch
  galaxy_tags:
    - clustering
    - system
dependencies: []
