---
- debug: 
    msg: "{{ ansible_distribution }}"

# tasks file for ansible-rabbitmq
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: >
        ansible_distribution == "CentOS" or
        ansible_distribution == "RedHat" or
        ansible_distribution == "OracleLinux"

- include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- include_tasks: config.yml
  when: rabbitmq_config_service

- name: checking to see if already clustered
  stat:
    path: /etc/rabbitmq/clustered
  become: true
  register: clustered

- include_tasks: rabbitmq_clustering.yml
  when: >
        rabbitmq_enable_clustering
        

- include_tasks: rabbitmq_vhosts.yml
  when: rabbitmq_extra_vhosts is defined

- include_tasks: rabbitmq_ha_config.yml
  when: >
        rabbitmq_config_ha and
        rabbitmq_enable_clustering and
        rabbitmq_config is defined

- include_tasks: rabbitmq_users.yml
  when: rabbitmq_users is defined
